### ISSUE TITLE
Servants and auto doors

### ISSUE THREAD

**Issue by AnsgarTOdinson** [Kaltharos/AutoCloseDoors#1]
Servants routinely make auto doors unable to open.

**Comment by Kaltharos** [comment]
I'm not able to reproduce this issue on my test server.
Servants open & close doors normally, and it doesn't make my door stuck.

**Comment by Kaltharos** [comment]
Spoke too soon!
Managed to reproduce the issue.

**Comment by Kaltharos** [comment]
Fixed in `1.0.2`
